### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by donny681** [wisdom-projects/holer-server#1]
您好，我设置了nginx还有数据库，按照你的教程ip地址无法访问holer-server，nginx能够80端口正常 访问，证明nginx配置没问题。但是运行了holer程序后，过了一会儿进程退出，也没有报错，请问怎么查看log信息

**Comment by xawangyd** [comment]
直接下载软件包
参考使用案例：
http://blog.wdom.net/category/Holer

**Comment by WisdomFamily** [comment]
请下载最新的代码编译启动
